# Ansible vars to use with the apps role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

BROWSERS_APPS:
  - google-chrome
  - zen-avx2-bin
  - brave-bin

CHAT_APPS:
  - slack-desktop
  - discord

DEVELOPMENT_APPS:
  - httpie
  - git
  - git-delta
  - lazygit
  - gh
  - fnm-bin
  - hyperfine
  - scc-bin

AI_APPS:
  - chatgpt
  - cursor
  - claude
  - gemini-cli

DATABASE_APPS:
  - pgcli
  - dbeaver

EDITORS_APPS:
  - visual-studio-code-bin
  - zed

INFRASTRUCTURE_APPS:
  - ansible
  - docker
  - docker-compose
  - docker-buildx

MULTIMEDIA_APPS:
  - mpv
  - spotify

SYSTEM_APPS:
  - noto-fonts-emoji

NPM_PACKAGES:
  - @github/copilot
OTHER_TOOLS:
  - nnn
  - tradingview
