# Ansible vars to use with the apps role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

BROWSERS_CASKS:
  - google-chrome
  - zen
  - brave-browser

CHAT_CASKS:
  - slack
  - discord
  - whatsapp

DEVELOPMENT_FORMULAS:
  - httpie
  - git
  - git-delta
  - lazygit
  - gh
  - fnm
  - oven-sh/bun/bun
  - scc
  - hyperfine

AI_FORMULAS:
  - gemini-cli
  - ollama

AI_CASKS:
  - chatgpt
  - cursor
  - claude
  - claude-code
  - steipete/tap/codexbar

DATABASE_FORMULAS:
  - libpq
  - pgcli

DATABASE_CASKS:
  - dbeaver-community

EDITORS_CASKS:
  - visual-studio-code
  - zed

INFRASTRUCTURE_FORMULAS:
  # - ansible
  - awscli
  - docker
  - docker-compose
  - docker-buildx

INFRASTRUCTURE_CASKS:
  - gcloud-cli

MULTIMEDIA_FORMULAS:
  - mpv

MULTIMEDIA_CASKS:
  - spotify

SYSTEM_FORMULAS:
  - tw93/tap/mole

SYSTEM_CASKS:
  - nikitabobko/tap/aerospace
  - font-fira-code-nerd-font
  - logi-options+

NPM_PACKAGES:
  - "@github/copilot"

OTHER_FORMULAS:
  - nnn

OTHER_CASKS:
  - tradingview
  - bitwarden
