# Ansible vars to use with the shell role
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)

---
FISH_PATH: /opt/homebrew/bin/fish

TERMINAL_APPS:
  - fish
  - fisher
  - --cask ghostty
  - starship
  - gnupg
