
# Ansible role to install and configure all development apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

# Install local packages depending on the platform
- block:
    - name: Load system variables
      include_vars: vars/linux.yml

    - name: Install browsers
      ansible.builtin.shell: bun install -g {{ item }}
      loop: "{{ NPM_PACKAGES }}"
  when:
    - ansible_os_family != 'Windows'
    - ansible_os_family != 'Darwin'

# Install local packages depending on the platform
- block:
    - name: Load system variables
      include_vars: vars/mac.yml

    - name: Install browsers
      ansible.builtin.shell: bun install -g {{ item }}
      loop: "{{ NPM_PACKAGES }}"

    - name: Configuring claude
      ansible.builtin.file:
        src: "{{ role_path }}/files/claude/settings.json"
        dest: "{{ HOME }}/.claude/settings.json"
        state: link
        force: true

  when: ansible_os_family == 'Darwin'
