# Ansible role to install and configure all development apps
# Author: Jose Manuel Rosa <jmanuelrosa@duck.com> (https://jmanuelrosa.dev)
---

- name: Load system variables
  include_vars: vars/main.yml

- name: Install npm packages
  ansible.builtin.shell: bun install -g {{ item }}
  loop: "{{ NPM_PACKAGES }}"

- name: Configuring claude
  ansible.builtin.file:
    src: "{{ role_path }}/files/claude/settings.json"
    dest: "{{ HOME }}/.claude/settings.json"
    state: link
    force: true
